<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SunmaoTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sunmao.Communication\Sunmao.Communication.csproj" />
    <ProjectReference Include="..\..\src\Sunmao.Testing\Sunmao.Testing.csproj" />
  </ItemGroup>

</Project>
