<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SunmaoTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sunmao.Diagnostics\Sunmao.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\Sunmao.Testing\Sunmao.Testing.csproj" />
  </ItemGroup>

</Project>
