<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SunmaoWindowsTargetFrameworks)</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sunmao.Wpf.Theme\Sunmao.Wpf.Theme.csproj" />
    <ProjectReference Include="..\..\src\Sunmao.Testing\Sunmao.Testing.csproj" />
  </ItemGroup>

</Project>
